#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
# -----------------------------------------------------------------------------
#
#    Copyright (c) 2016+ Type Network
#
#
# -----------------------------------------------------------------------------
#
#    python setup.py py2app
#

"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app
"""

from setuptools import setup


setup(
    app=['delegate.py'],
    name="AppDelegate",
    data_files=['en.lproj'],
    setup_requires=['py2app'],
    options=dict(py2app=dict(#iconfile='en.lproj/icon.icns',
        packages=['pkg_resources'],
        resources=[resources])
    )
)
